img_width = 300
img_base_url = 'https://raw.githubusercontent.com/flyingcakes85/Anime-Boys-Holding-Programming-Books/main'
img_small_base_url = "/"
template_path = '/tmp/riku-anime-boys-template'
output_folder = '.www'
